## What is NumPy-
1. Numpy is the Python Library used to work with arrays .
2. It has also working domains with linear algebra, fourier transform and matrices .
3. NumPy stands for Numerical Python.

## Why Python is Used ?
1.In Python we have lists which serves as arrays but they are slow to process.
2.NumPy provides the object array which is 50 times faster than tarditional lists.
3.The array object in NumPy is called as ndarray.It provides many supporting function which makes it easy to work with ndarray. 
4.


## Why NumPy is faster than Lists ?
1.NumPy arrays are stored in one continuous place in memory unlike Lists so processes can access and manipulate them efficiently.This behaviour is called locality of refrence in Computer Science . This is the main reason for NumPy to be faster than Lists.
2.

## Working with NumPy-

In [2]:
import numpy as np     # 0-D array.
a=np.array(43)
print(a)

43


In [5]:
b=np.array([23,433,12,1323,434])   # 1-D array
print(b)

[  23  433   12 1323  434]


In [9]:
c=np.array([[1,2,4],[23,44,56]])   # 2-D  array
print(c)
c.ndim

[[ 1  2  4]
 [23 44 56]]


2

In [10]:
d=np.array([[[23,44,55],[12,55,77,]],[[455,223,12,],[231,45,2,]]]) #3-d array
print(d)
d.ndim

[[[ 23  44  55]
  [ 12  55  77]]

 [[455 223  12]
  [231  45   2]]]


3

In [11]:
print(c[0,2]) # Indexing in 2-d array.

4


In [12]:
print(d[1,1,2]) #Indexing in 3-d  array

2


In [19]:
print(b)        # Slicing in 1-D array
print(b[1:4]) 
print(b[0:4:2]) 
print(b[:3])
print(b[2:])
print(b[::3])

[  23  433   12 1323  434]
[ 433   12 1323]
[23 12]
[ 23 433  12]
[  12 1323  434]
[  23 1323]


In [26]:
print(c)                # Slicing in 2- D array.
print(c[1,0:2])
print(c[0:1,0:1])
print(c[0:2,1])
print(c[0:2,1:])

[[ 1  2  4]
 [23 44 56]]
[23 44]
[[1]]
[ 2 44]
[[ 2  4]
 [44 56]]


In [28]:
arr = np.array([1, 2, 3, 4], dtype='S') # Data types in NumPy 

print(arr)


[b'1' b'2' b'3' b'4']


In [31]:
arr=np.array(["bar","car","train"])
arr.dtype

dtype('<U5')

In [33]:
n=np.array([1,2,3,4])
x=n.astype('S')
x

array([b'1', b'2', b'3', b'4'], dtype='|S11')

In [39]:
ar=np.array([1,2,3,4,5]) # copy() used to copy the content of array 
x=ar.copy()
print(x)
y=ar.view()      # view() is just used to view the data it does not stores the data 
print(y)

[1 2 3 4 5]
[1 2 3 4 5]


In [42]:
#Changes done in original or  copy of array does not effects the other but changes in original or view changes the other.
x[2]=23  # No change in ar even when change done in copy beacuse the copy stores its own data.
print(ar)
print(x)

[1 2 3 4 5]
[ 1  2 23  4  5]


In [44]:
y[3]=44  # Changes done in view() changes the original array as well and vice-versa because view() does not stores its own data.
print(y)
print(ar)

[ 1  2  3 44  5]
[ 1  2  3 44  5]


In [45]:
ar.shape # shape tells us the shape of array.

(5,)

In [50]:
n=np.array([[1,2,3,4],[44,55,66,77]])
n.shape

(2, 4)

In [52]:
s=np.array([1,2,3,4,5,6,7,8,9]) # re-shaping the 1-D array into 2-D array. 
m=s.reshape(3,3)     # we provide parameters through argument that how many dimension and how many elements in each dimension. 
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
t=s.reshape(3,3,1) #changing 1-D array into 3-D array.
t

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [57]:
r=t.reshape(-1)  # for flattening the array into 1-D array.
r

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
for x in t:            # iterating in 3-D array .
    for y in x:
        for z in y:
             print(z)

1
2
3
4
5
6
7
8
9


In [66]:
for x in np.nditer(t): # np.nditer() helps to iterate each element inside multidimensional array without writing n loops steps.
 print(x)

1
2
3
4
5
6
7
8
9


In [8]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=2, mode='constant', constant_values=np.nan)
print(Z)

[[nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan]
 [nan nan  1.  1.  1.  1.  1. nan nan]
 [nan nan  1.  1.  1.  1.  1. nan nan]
 [nan nan  1.  1.  1.  1.  1. nan nan]
 [nan nan  1.  1.  1.  1.  1. nan nan]
 [nan nan  1.  1.  1.  1.  1. nan nan]
 [nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan]]


In [18]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [21]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1

print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
Z = np.tile( np.array([[0,1],[1,0]]), (5,5))
print(Z)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


In [32]:
z=np.arange(5)
x=np.zeros((5,5))
y=z+x
y
t=y.astype(int)
print(t)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [33]:
from numpy import random

In [49]:
Z = np.random.rand(2,3)
print(Z)

[[0.29096233 0.85934225 0.23211317]
 [0.57983455 0.79538502 0.19065775]]


In [57]:
A = np.random.randint(2, size=(2,4))
B = np.random.randint(2, size=(2,6))
print(A)
print(B)

[[0 0 0 0]
 [1 0 0 1]]
[[0 0 0 1 0 0]
 [0 0 0 1 1 1]]


In [65]:
a=np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Wall time: 0 ns


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])